import type { DirectorySummary, StaffDirectoryRow } from "./types";

export const DIRECTORY_SUMMARY: DirectorySummary = {
  activeStaff: 50,
  activeStaffLabel: "Currently employed",
  coriAlerts: 29,
  coriExpired: 12,
  authPending: 0,
  authPendingLabel: "CORI auth forms sent, awaiting upload",
  suspended: 1,
  suspendedLabel: "On leave or suspended",
  terminated: 30,
  terminatedLabel: "Former employees",
  newThisMonth: 0,
  newThisMonthLabel: "Recently hired",
};

export const MOCK_STAFF: StaffDirectoryRow[] = [
  {
    id: "1",
    name: "Ruben Alamo",
    status: "active",
    role: "Maintenance & Housekeeping",
    department: "Maintenance",
    permissionGroup: "No Access",
    email: "rubenalamo2123@gmail.com",
    hireDate: "Mar 26, 2021",
    firstName: "Ruben",
    lastName: "Alamo",
    personalEmail: "rubenalamo2123@gmail.com",
    businessEmail: "rubenalamo2123@gmail.com",
    cellPhone: "",
    smsConsent: false,
    employmentType: "Full Time",
    workSchedule: "",
    hireDateIso: "2021-03-26",
    originalHireDateIso: "",
    probationEndDateIso: "",
    flsaStatus: "Non-Exempt",
    workLocation: "",
  },
  {
    id: "2",
    name: "Sally-Rose Banda",
    status: "active",
    role: "Server",
    department: "Dietary",
    permissionGroup: "No Access",
    email: "sallyrose@example.com",
    hireDate: "Jun 12, 2022",
    firstName: "Sally-Rose",
    lastName: "Banda",
    personalEmail: "sallyrose@example.com",
    businessEmail: "sallyrose@example.com",
    cellPhone: "",
    smsConsent: true,
    employmentType: "Full Time",
    workSchedule: "",
    hireDateIso: "2022-06-12",
    originalHireDateIso: "",
    probationEndDateIso: "",
    flsaStatus: "Non-Exempt",
    workLocation: "",
  },
  {
    id: "3",
    name: "Katherine Barahona",
    status: "active",
    role: "Server",
    department: "Dietary",
    permissionGroup: "No Access",
    email: "kbarahona@example.com",
    hireDate: "Aug 3, 2019",
    firstName: "Katherine",
    lastName: "Barahona",
    personalEmail: "kbarahona@example.com",
    businessEmail: "kbarahona@example.com",
    cellPhone: "",
    smsConsent: false,
    employmentType: "Part Time",
    workSchedule: "",
    hireDateIso: "2019-08-03",
    originalHireDateIso: "",
    probationEndDateIso: "",
    flsaStatus: "Non-Exempt",
    workLocation: "",
  },
];

export function createEmptyStaff(): StaffDirectoryRow {
  return {
    id: `new-${Date.now()}`,
    name: "",
    status: "active",
    role: "",
    department: "",
    permissionGroup: "No Access",
    email: "",
    hireDate: "",
    firstName: "",
    lastName: "",
    personalEmail: "",
    businessEmail: "",
    cellPhone: "",
    smsConsent: false,
    employmentType: "Full Time",
    workSchedule: "",
    hireDateIso: "",
    originalHireDateIso: "",
    probationEndDateIso: "",
    flsaStatus: "Non-Exempt",
    workLocation: "",
  };
}
